import React from 'react';
import { Container } from 'reactstrap';
import '../../App.css';
window.addEventListener("message",e=>{e['data']&&"6877412"===e['data']['id']&&document.getElementById(`${e['data']['id']}`)&&(document.getElementById(`${e['data']['id']}`).style.height=`${e['data']['frameHeight']+30}px`)})
window.addEventListener("message",e=>{e['data']&&"6877414"===e['data']['id']&&document.getElementById(`${e['data']['id']}`)&&(document.getElementById(`${e['data']['id']}`).style.height=`${e['data']['frameHeight']+30}px`)});
function Thinking() {
  return (
    <>
<div class="subject">
    <Container>
    <h1>Thinking in chess</h1>
    <p>In my experience teaching, playing, and hanging out at the local chess club, I have come across many players who succeed in reaching a level in the 1600-2000 range&nbsp;<strong>but</strong>&nbsp;<strong>get stuck, often for life, trying to get beyond that and become an expert or master</strong>. My aim is to give you tools to take your game to that next level.</p>
<p>Let's tackle the problem of&nbsp;<strong>how to think in chess.</strong></p>
<p>The topic is not as ridiculous as it sounds. What I'm really talking about is a static and general mode of thinking vs. a dynamic and specific one.</p>
<p>Players in the 1600-2000 skill range have generally mastered the strategic fundamentals of openings, middlegames, and endgames and are aware of these principles during their games. However, the problem that plagues many players at this level and prevents them from improving further is that they think&nbsp;<strong>only</strong>&nbsp;in terms of these general principles.</p>
<p>Listen to a postmortem between two class players after a tournament game. You will hear many generalities, e.g. "Well I thought if I put my knight in the center, it will later be useful in an attack."&mdash;"Yes, but I thought if I saddle you with an isolated pawn, I can take advantage of it in the endgame."</p>
<p>The discussion consists almost entirely of general ideas that apply in any position.</p>
<p>Do you see what's missing from the analysis?&nbsp;<strong>Specific lines</strong>. In contrast, listen to two masters analyzing, and you will hear both of them spouting moves and variations. It's not that general principles don't apply beyond a certain level; it's that stronger players apply these principles according to the specific needs of the position.</p>
<p>To progress to expert and master, it's crucial to move beyond vague generalities and learn to think specifically about the position in front of you, as well as dynamically, i.e. in terms of specific moves.&nbsp;<strong>Calculation</strong>&nbsp;must become a major part of your thought process. Failing to do so will result in missing resources, for both yourself and your opponent, tactical errors, and outright blunders.</p>
<p>&nbsp;</p>
<iframe id="6877414" title="thinking1" allowtransparency="true" frameborder="0" style={{width:"100%"}} src="//www.chess.com/emboard?id=6877414"></iframe>
<p>Thinking in generalities and insufficient calculation come up at higher levels as well, although in more subtle ways. For the second example, I would like to show a segment from one of my own recent games.</p>
<p>&nbsp;</p>
<iframe id="6877412" title="thinking2" allowtransparency="true" frameborder="0" style={{width:"100%"}} src="//www.chess.com/emboard?id=6877412"></iframe>
<p>As you can see, making decisions based only on general principles and ideas leads to errors and ultimately loses games. To improve your approach to the game, and your results these are the steps I would like you to take:</p>
<ul>
<li>Do not abandon fundamental principles, but look for a move that's based on a good idea&nbsp;and leads to a specific follow-up in order to achieve a specific goal in the given position (rather than making a move only to fulfill an idea). For example, instead of thinking "I will play Re1 because a rook belongs on an open file," you would approach it as, "Re1, putting the rook on an open file, will enable (moves X, Y, Z) in order to (start a kingside attack / win a pawn / etc.)."</li>
<li>Identify specific threats, both for you and for your opponent. Come up with several candidate moves. Then identify candidate responses for your opponent to each of your candidate moves. Look for the best move for&nbsp;both sides.&nbsp;Calculate variations. Practice doing this on every move.</li>
<li>To emphasize the point again: Get into the habit of&nbsp;calculating. I'm not even asking you to calculate&nbsp;accurately. That's important, but it's the next step. The first step is to train yourself to calculate, period.</li>
</ul>
<p>The primary guiding principle of analyzing your opponent&rsquo;s threats, weaknesses, and potential plans first before looking at your own, should have, in the first example, lead to the realization that the back rank was undefended. This tells us defense is in order and so quiet positional improvements were probably not going to be part of the main plan, leaving only more active plans as viable ones.<br />Once this was known it could then have been determined whether or not whites threat was stronger and would have come faster than blacks, thus defending indirectly through an offensive threat. Otherwise, it would be clear that white must defend in a more direct way, such as blocking the immediate threat with Rg7 to f7, or by moving the King to a safer square, or perhaps by making an even better move. Calculations could have been made for each candidate move to determine which line of attack and/or defense worked best as a plan of action and then the right move could have been made. If you missed the main idea, you learn something, often making you a better player on the spot. If you had the right idea but failed to calculate correctly, ask yourself, in what way was the calculation inaccurate? Was it a visualization error such as not mentally moving or removing pieces properly in the mind, was it a working memory capacity issue, a failure to recognize an important in-between move, was it a pattern recognition issue, or was it ultimately a failure to take stock of the resulting position at the end of those moves and to properly assess whether or not that resulting new position was in your favor. Was it something else entirely or maybe several things? Once you come to understand what caused the inaccuracy, ask yourself how you could prevent that from happening in the future and then test your idea for prevention to see if it works or if something else is needed. Reiterate until you find a way to strengthen the weakness in calculation ability.</p>
<p>Obviously, to play chess well requires time and if you don't have the time to work through the position properly then you must risk making an error, so you must decide whether or not to make the safest move you can, or to make the most complicated move you can, providing sauce for the goose. The lack of speed, even if play is accurate, leads to time trouble and loss. Proper and consistent study, practice, and plenty of solid post game analysis, eventually leads to the ability to be accurate in all situations you might encounter. Speed follows accuracy over time as you practice drills, learn new material, and analyze your play until you reach your peak in both speed and accuracy, at which point you cannot continue to make improvements. Often people think they've reached their peak without looking into ways to expand their capacity for working memory, long term memory, and visualization skills. There may be ways to sharpen and optimize your cognitive abilities or ways that allow you to think more creatively.</p>
<p>When people speak of general guiding principles and the correct way to think when playing chess, this is what I think they are referring to. What it seems they are referring to instead are situations where there are competing principles involved and you need to determine through analysis, which should be followed, and which should be ignored or treated as secondary in a given situation. There are always competing ideas, finding and correctly executing the best ones are what champions do better than their opponents. I'm not certain that computers have ideas, but a good one can beat you like a drum and leave you bleeding out of both ears.</p>
<img src="https://images.chesscomfiles.com/uploads/v1/article/17623.87bb05cd.668x375o.47d81802f1eb@2x.jpeg" alt="chess"/>
<p><h2>How important is to be well prepared?</h2></p>
<p>I am assuming you are below 2100 fide and you are trying to improve. However, in my opinion openings do not matter as much as you would think at this level. So my recommendation will be to be &ldquo;well prepared&rdquo; but not overly prepared as you would probably just waste your studying time for nothing as other areas in your game probably need much more attention.</p>
<p><h2>What to play as white</h2></p>
<p>As white, I recommend that you specialize in one line. It&rsquo;s difficult to perfect e4 and d4 simultaneously, and it would be the wrong strategy. 1c4 goes along with d4, so it can be included, but rh2h2ber , you have to specialize!</p>
<p>In my case I only play 1d4 as white. And it&rsquo;s probably my most solid part of the repertoire. I tend to win more games as white than I do with black. Funny enough I probably do little study on the white side. I tend to get good positions and decent ways to play for a win, and I am rarely in trouble with the white pieces. So I tend to study very little lines with 1d4.</p>
<p><h2>What to play as black</h2></p>
<p>I recommend that you put all your attention of your studying time in the openings to the black repertoire. You need to be very well prepared against anything that white throws at you. In my case I play ...1e5 against 1e4 and 1&hellip;Nf6 against 1d4, trying to get nimzo, bogoindians or similar variants. For my preparation, having a solid repertoire as black was the most challenging. There were so many positions that you need to get accustomed to (especially if you play &hellip;1e5) that it took me some time before I could start to call my openings as black &ldquo;solid&rdquo;.</p>
<p>As black you may want to have 2 weapons, a solid choice and an aggressive one. For example you might consider &hellip;1e5 solid. And if you would like to surprise your opponent choose the Alekhine &hellip;1Nf6 as your second choice.</p>
<p><h2>How to study openings?</h2></p>
<p>You need to be wise as how you study openings. I don&rsquo;t recommend that you buy opening books until you hit 2100, and if you do so, not more than 3 or 4 books. Use thh2 as a reference on your preferred lines but do not try to mh2orize anything from the book! This would be the wrong approach.</p>
<p>If you want to get more knowledge on openings, a simple database will do the work. You don&rsquo;t need to buy anything fancy (megadatabase 2014 etc), chessth2po has an online free database with an opening book showing most popular moves played with performance and results attached to each move.</p>
<p><h2>Selecting lines and building the repertoire</h2></p>
<p>I recommend that you play a lot of training games online (FICS server is great free place to play), standard 15min or more. Try to practice openings in these games as if it was an OTB game. You will learn a lot, I guarantee. After each game research the opening, and try to find ways to improve on the position you got. Maybe you got out of the opening and you didn&rsquo;t like the type of position you got. That&rsquo;s a good sign that something can be improved. I assure you, there are enough possibilities in chess as to give you a way to play always positions that you feel comfortable in. There is always more certainly, a solid line, a risky line, a passive but easy to play line, an ambitious line with goods chances for win, etc&hellip; And you have to choose with what suits your style. Don&rsquo;t try to mh2orize too much if anything. You have to learn ideas in openings; these get stuck in your mind. Like, &ldquo; I play the knight to a5 reroute it to this square to control this other square blabla&rdquo; This is the way to learn, by learning ideas. Don&rsquo;t try to get too deep in any opening, you will certainly forget all the possible plans and you will waste your time. However, if you find that an opening gets played a lot to you, up to move 10-15, then its time to look deeper and learn 3-4 moves ahead. Don&rsquo;t try to cover everything, practice will show you the way of the things you need to improve. Learning openings is an open process which never ends, the more you play the more knowledgeable you will become. So experience plays a big role here.</p>
<p><h2>Preparing for an opponent in an OTB game</h2></p>
<p>As tournament players, this is a must for everyone. I will give you two tips:</p>
<p>1)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Try to guess what your opponent is likely to play by looking at his games</p>
<p>2)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Prepare one or two lines he might play, by looking a chess database</p>
<p>In preparing lines to play, I recommend to select lines that make you feel comfortable. Try to avoid your opponent preparation and bring him to your territory. Select lines that he might not know too well and propose problems.</p>
<p>Play one or two 15 min games versus Houdini engine, in the most like variation he will play, just to get a feeling of the type of position that will arise in the OTB game. This will help a lot.</p>
<p><h2>Learn something useful, learn endings!</h2></p>
<p>I cannot overstate the importance of studying endings. The most efficient and rewarding way of studying chess is to learn endings. Learning endings has made not just a better player in endings, but a better player in chess overall. By learning endings I don&rsquo;t mean that you buy the latest ending manual of Dvoretsky book and you go page by page. I don&rsquo;t think this is the right approach. You can learn endings in a cheap way without books. But if you really want to buy a book that will change the way you think about chess, buy Sherevesky books on practical endings.</p>
<p>Again I&rsquo;m going to recommend that you play a lot of training games 15 min or longer with increment online. Try to play the endings the best possible way you can. If you are up a pawn, try to convert it to a win, and don&rsquo;t give up by submitting to a draw.</p>
<p>Afterwards, it&rsquo;s time to analyze. If it was a trivial win, let&rsquo;s say two pawns up. Review it briefly and then move on to the next game. Try to review the game on your own, the learning experience will be greater. Bring the engine only when you have no clue on the position.</p>
<p>Now you played an interesting game, with a complex ending with winning chances. You didn&rsquo;t convert. Now devote 30min-1h to study this ending. Try to figure out on your own the best plans, only then research with an engine. Most likely there would be 1 or 2 key moments in the ending that you misplayed. Focus on this, and try to visualize a winning plan or a drawing plan. Once you get a conclusion, &ldquo; I should have cut off the king from the 5<sup>th</sup>&nbsp;rank, and activate my rook,etc&hellip;&rdquo; move on to the next game, and hope you will get a game worth of analyzing.</p>

</Container>
</div>
</>
);
}

export default Thinking;
